name: 'tfh-rpm-action'
description: 'Build rpm package.'
author: 'team-fuho'
inputs:
  summary:
    description: 'Package summary.'
    required: true
  package:
    description: 'Package name of rpm package.'
    required: true
  package_root:
    description: 'Directory of release files.'
    required: true
  maintainer:
    description: 'Package maintainer name.'
    required: true
  vendor:
    description: 'Package vendor.'
    default: ''
  version:
    description: 'Package version.'
    required: true
  arch:
    description: 'Package architecture.'
    default: 'x86_64'
  desc:
    description: 'Package description.'
    default: ''
  license:
    description: 'Package LICENSE.'
    default: 'MIT'
  post:
    description: 'Package post.'
    default: ''
  build_requires:
    description: 'Package build requires.'
    # NOTE: for nim parseops package bugs
    default: '-'
  requires:
    description: 'Package requires.'
    # NOTE: for nim parseops package bugs
    default: '-'
outputs:
  file_name:
    description: 'File name of resulting .rpm file. This does not contain a debuginfo file.'
  debuginfo_file_name:
    description: 'File name of resulting .rpm debuginfo file.'
runs:
  using: 'docker'
  image: 'docker://team-fuho/tfh-rpm-action:2.5.2'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
