name: Test
on:
  push:
  pull_request:
jobs:
  test-script:
    name: runner / build-deb-action (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/testbin
          echo -e "echo hello" > .debpkg/usr/bin/testbin
          echo -e "echo hello2" > .debpkg/usr/bin/testbin2
          echo -e "a=1" > .debpkg/usr/lib/testbin/testbin.conf
          chmod +x .debpkg/usr/bin/*
      - uses: ./
        with:
          package: testbin
          package_root: .debpkg
          maintainer: jiro4989
          version: 'v1.0.0'
          arch: 'amd64'
          desc: 'test package'
      - name: install deb package
        run: sudo dpkg -i *.deb
      - name: check files
        run: |
          which testbin
          testbin
          which testbin2
          testbin2
          find /usr/lib/testbin/
          cat /usr/lib/testbin/testbin.conf

  test-nim-package:
    name: runner / build-deb-action (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: |
          git clone https://github.com/jiro4989/nimjson app
          pushd app
          nimble build -Y
          cp bin/nimjson ../
          rm -rf app
          popd

          mkdir -p .debpkg/usr/bin
          mv nimjson .debpkg/usr/bin/
      - uses: ./
        with:
          package: nimjson
          package_root: .debpkg
          maintainer: jiro4989
          version: 'v1.0.0'
          arch: 'amd64'
          desc: 'test package'
      - run: sudo dpkg -i *.deb
      - run: which nimjson
      - run: nimjson -h
