name: Test
on:
  push:
  pull_request:
jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/testbin
          echo -e "echo hello" > .debpkg/usr/bin/testbin
          echo -e "echo hello2" > .debpkg/usr/bin/testbin2
          echo -e "a=1" > .debpkg/usr/lib/testbin/testbin.conf
          chmod +x .debpkg/usr/bin/*
      - uses: ./
        with:
          package: testbin
          package_root: .debpkg
          maintainer: jiro4989
          version: 'v1.0.0'
          arch: 'amd64'
          desc: 'test package'
      - run: |
          docker run --rm -v $PWD:/work -it centos:7 bash -c 'rpm -Uvh /work/*.rpm && which testbin && testbin'

  test-nim-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: |
          git clone https://github.com/jiro4989/nimjson app
          pushd app
          nimble build -Y
          cp bin/nimjson ../
          rm -rf app
          popd

          mkdir -p .debpkg/usr/bin
          mv nimjson .debpkg/usr/bin/
      - uses: ./
        with:
          package: nimjson
          package_root: .debpkg
          maintainer: jiro4989
          version: 'v1.0.0'
          arch: 'amd64'
          desc: 'test package'
      - run: |
          docker run --rm -v $PWD:/work -it centos:7 bash -c 'rpm -Uvh /work/*.rpm && which nimjson && nimjson -h'
